### ISSUE TITLE
Make work with shows that use dates instead of S01E01

### ISSUE THREAD

**Issue by 8cylinder** [8cylinder/tv-overlord#11]

**Comment by poo706** [comment]
I was thinking about this. Maybe you could add another column to the database for "search by air date".  I presume you already collect the air date of a show in a variable so that tvol knows when to search for it.  When it goes to search for a show, it could check the flag in the database and search by air date instead.

**Comment by poo706** [comment]
I came up with a way to make tvol (in conjunction with my bash script) search for the Daily Show by air date automatically, at the appropriate times, and with database updates.  I have the Dailiy Show active in the database like any other show and it won't ever find it during a normal `tvol download`.  But then I have my script parse `tvol list` for new Daily Show episodes.  I take that data and look up the air dates on tvdb, then do a `tvol nondbshow` with the air date.  The bash script checks the number of files in the nzb/magnet destination folder before and after the nondbshow search, and if they don't match, the database is updated with the season and episode number that was just downloaded.  It won't have a problem with new season numbers and it won't have a problem with preceding 0's on episodes 1-9.  It was really entirely unnecessary, I just wanted to see if I could do it.

**Comment by 8cylinder** [comment]
tvol now supports shows that use dates instead of season, episode.  I haven't put it up on pypi yet since it needs some more testing but so far it seems to work.  The latest commit (9679f5222d3122b9a07a4f3255a5c31c49fe1e3f) has the changes.  

The way it works:

1. Add a show that uses dates. eg:
   Jeopardy, The Late Show with Stephen Colbert
2. `tvol editshow jeopardy`.  In the line that says `Search by date (n) [y/n]` type `y`
3. Add a custom format string if necessary.

tvol defaults to using `yyyy mm dd` as part of the search.  The search string used for Jeopardy would look like this: `jeopardy 2016 11 29`.  Using `yyyy mm dd` finds the broadest results but in the case of Jeopardy it doesn't work very well.  Who ever is uploading it uses this date style: `Nov 24 2016`.  So there is a second field where you can specify a custom format string.  It uses the Python [date format syntax](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior).

Some show use `yyyy-mm-dd` or `yyyy.mm.dd`.  Changing the separator might give better results.

Some examples:

`%Y %m %d` = `2016 11 01`
`%Y.%m.%d` = `2016.11.01`
`%b %d %Y` = `Nov 01 2016`
`%b %-d %Y` = `Nov 1 2016`

Note the `-` before the `d`, this removes the leading `0` (this might not work on windows).

If anyone wants more examples or has shows that they can't get working let me know.

**Comment by poo706** [comment]
Sounds awesome, can't wait to try it!
