### ISSUE TITLE
Add option to print magnet link

### ISSUE THREAD

**Issue by brenthuisman** [8cylinder/tv-overlord#23]
For clients that can't register as handler.

**Comment by 8cylinder** [comment]
tvol has the option to create text files with the magnet link in them and put them in a dir, would that solve the problem?

In [config.ini](https://github.com/8cylinder/tv-overlord/wiki/Config-file):

`magnet folder: ~/some/dir`

Or do you have a use case where that wouldn't work?

**Comment by brenthuisman** [comment]
I didn't see that option, not bad! My client doesn't seem to read .magnet files however (I hadn't seen them so far either). A printed checksum to screen would work in any case, but I understand it's probably a very specific issue not affecting any others.

**Comment by 8cylinder** [comment]
TV Overlord only uses magnets or nzb's so if you client doesn't support those then tvol won't work for you unfortunately.

**Comment by brenthuisman** [comment]
Well, the client supports magnets, but only as text entry, not file.
