### ISSUE TITLE
Add command to remove a show

### ISSUE THREAD

**Issue by eleijonmarck** [8cylinder/tv-overlord#24]

**Comment by 8cylinder** [comment]
Right now that is handled by using `editshow` which is an interactive command.

`tvol editshow "show name"`

Then by setting the `status` to `inactive`. That doesn't actually delete the show from the db, but it will look like it was.

You can list the inactive shows with:

`tvol info --status=inactive --show-all`

Does that work or do you need a way to do it non-interactively?

**Comment by eleijonmarck** [comment]
Hey! I just played around with it now and noticed that you could change it to inactive.

The first time I got it; I might have been a little too excited and added a bunch of shows but it became kinda long when I needed to download and go through them all.

But I still would like to have a way of deleting the shows after you have seen the tv show. So for instance that you wanted to look at a complete new series. Watch them for 5 days straight ( some people do that.... ) =)

Otherwise maybe just a note on how to set the status of the show in the documentation would be great.

Thank you for this amazing CLI. Love it!

**Comment by 8cylinder** [comment]
Yeah, the documentation really needs some work.  Having all these new users has really shown me whats confusing and needs to be fixed up.
