### ISSUE TITLE
Core generated.

### ISSUE THREAD

**Issue by juanvelascogomez** [8cylinder/tv-overlord#25]
![1](https://cloud.githubusercontent.com/assets/7736733/17773661/a7196600-654f-11e6-98c7-499b39597426.png)

Problem downloading Mr Robot episodes, failed. Core generated.

**Comment by 8cylinder** [comment]
I need some more information.

1. What platform are you using?
2. Do other shows work or do they all fail?

**Comment by juanvelascogomez** [comment]
Im using Antergos (Arch Linux). I added another show but same issue when doing tvol download

**Comment by 8cylinder** [comment]
I'm pretty sure you are having this issue: "#13 Segfault when using the download command".

First, install it in a virtualenv to see if that works.  If it does, then there is a problem with some of the python packages installed with pacman.  I don't use Arch, but from what the other user said, pacman was installing dev versions of some packages.  Take a look at that thread and see if it helps.

**Comment by 8cylinder** [comment]
If you are still having problems, re-open this issue.
