### ISSUE TITLE
Non X usage is not supported

### ISSUE THREAD

**Issue by jrdiniz** [8cylinder/tv-overlord#26]
Hi,

When I select a episode to download I receive this message: Non X usage is not supported

I'm using a raspberry pi with ubuntu 16.04.

**Comment by 8cylinder** [comment]
If there is no default handler for magnet links (which is set by a desktop enviroment) then the following two settings in config.ini determine what to do when an episode is downloaded.  If "magnet folder" is set, it will be used.  If not, then the "client" setting is used.  If client is not set, then the default bittorent client is used.

- `magnet folder: FOLDER`
   if set to a folder name, the downloaded magnet links will be written to this folder, one file for each episode.  The file will have the magnet link as its contents and look like this: `Family_Guy_S09E12.torrent`.

- `client: COMMAND`
   If this is set, it will override the default client for your os. This can be used to run a command line bittorrent client.  It must have this flag as part of it: {magnet}, which will get replaced with the downloaded magnet link.  Also, any file paths with a space must be enclosed in quotes.  The `{magnet}` tag can be used more than once if necessary.

   example: `client: transmission-cli --download-dir "/home/ricka/tv shows" {magnet}`

Re-open this bug report if that doesn't work for you.

**Comment by jrdiniz** [comment]
Thanks, works for me :-)
