### ISSUE TITLE
Modify Provider List

### ISSUE THREAD

**Issue by xealot** [8cylinder/tv-overlord#27]
Am I missing this in the documentation or command structure somewhere?

Some providers are slow, and I never pick them anyway. Would be nice to disable those. 

As a future feature idea, offer prioritized search providers and keep most of the list as a fallback incase no matches.

**Comment by 8cylinder** [comment]
Yeah, that should be a setting.  I think I'll put a `disabled search engines:` field in config.ini.

**Comment by xealot** [comment]
If the configuration was always pulled from disk, or serialized out somewhere it could just be a matter of commenting out the search engine.

Adding an exclusion list would solve my problem but it's a little strange that there is a fixed list that you have to exclude from.

**Comment by 8cylinder** [comment]
Well.., there has to be a list somewhere, if it's in code or read from some resource file it doesn't really matter.  How else would you do it?

I think having it default to all the search engines (or at least the ones I thinks work ok - not all of them do) but allowing the end user to prune that list if they want makes sense.  I think the end user shouldn't have to edit any other files other than config.ini. 

In the meantime, you want you can edit line 42 of search.py to change the list.

**Comment by xealot** [comment]
What I'm suggesting is if your list came from a configuration file that the user could edit, instead of creating a blacklist you could simply comment out the line in the config file for that provider.

```ini
[providers]
wanted=provider
;unwanted=provider
```

The alternative being:
1. load a hard coded list
2. apply blacklist
3. deal with possible typo in blacklist if misspelled

**Comment by 8cylinder** [comment]
Yeah, what you're saying makes sense.  I was thinking it add too much clutter in the config file for something most users probably wouldn't care about.

One issue with having a whitelist in the config file is that the search engines come and go fairly frequently.  So, after a couple of updates that config file would not reflect the current state of search engines.  I would still use the new ones but if the user wanted to remove one of the engines, they would have to add it manually to the list and then comment it out, kinda clunky.

**Comment by xealot** [comment]
I suppose if engines rapidly and constantly change then perhaps just offering a blacklist would be a better move. That way there isn't any complexity around keeping the list up to date in spite of a user's modified config file.

**Comment by 8cylinder** [comment]
I think I'll go ahead and add a blacklist method (after I think about it for a while), but if you think of any good ideas, I'd like to hear them.

**Comment by 8cylinder** [comment]
Fixed in dev branch: a099febf15e5c46251c75655ef97496cf9ccfade
