### ISSUE TITLE
Doc issue perhaps? Where do downloads go by default

### ISSUE THREAD

**Issue by arnicas** [8cylinder/tv-overlord#29]
Just trying this out... I don't have another torrent download executable or script on my Mac.  Where will it put the downloads by default?  (Or, do I need another tool for the actual downloading?)  I wasn't entirely sure because I got what looked like errors saying files or paths didn't exist when I picked a letter to download from the available torrent files list.

Maybe a simple FAQ doc fix for this?

**Comment by 8cylinder** [comment]
You need to have a bittorrent client installed.  TV Overlord passes your search to your installed client, then the client handles the downloading of tv episode.

These are a couple of bittorent clients that are good:

- [Transmission](https://www.transmissionbt.com)
- [Deluge](http://deluge-torrent.org)
