### ISSUE TITLE
searching added shows isn't always accurate

### ISSUE THREAD

**Issue by pketh** [8cylinder/tv-overlord#30]
I both have `Top Gear` and `Top Gear: Extra Gear` . I can't edit `Top Gear` because `tvol edit show 'top gear'` always brings up extra gear. 

I've also tried stuff like `top ge` to trick it to work, but always goes for the longer title

**Comment by 8cylinder** [comment]
That is definitely a problem.  Thanks for the report.

**Comment by 8cylinder** [comment]
Fixed in dev branch: 5c1c9b0af312e9ea9708567dd30ae27439cb50b0
