### ISSUE TITLE
tvol gets stuck when tvdb is slow

### ISSUE THREAD

**Issue by poo706** [8cylinder/tv-overlord#31]
I ran a "tvol download" and there was a long pause before I got a message about tvdb being slow or non-responsive.  I then went to the website just fine and pinged it just fine.  Fine, momentary tvdb glitch, I'll buy that.  However, from that point on it would return the same message every time I did "tvol download", and it would do it immediately.  A reboot fixed the issue.

**Comment by 8cylinder** [comment]
I have had problems with theTVDB.com api, sometimes it looks like it flakes out or stops responding.  In the past it's been pretty unreliable but in the last couple if years its worked reliable for me.  If this issue continues to happen then there is a problem with tvol.

One possible thing that might help when this happens is to run `tvol --no-cache <command> ...`.  The tvdb data is cached for about 4 hours and this invalidates the cache and fresh data is downloaded.

I'm going to mark this as closed, but if this happens again re open it and we'll try and figure out what's going on.

**Comment by poo706** [comment]
Sounds good, will do.  The way that there was a long pause the first time (legit tvdb issue) and no pause all the rest of the times (no real tvdb issues) makes me think that a variable isn't getting unset and that is causing tvol to jump to the error output before it has a chance to try accessing tvdb again.

**Comment by 8cylinder** [comment]
What happens the first time you run it, it downloads a bunch of data (and caches it) and if the server is slow, tvol will be slow.  If you run it again (within four hours) it reads from the cache instead of downloading from thetvdb.  The cache reads are super fast.
