### ISSUE TITLE
Post download script wiki issue

### ISSUE THREAD

**Issue by erikdsjostrom** [8cylinder/tv-overlord#37]
When adding the post download script to transmission I've found that on Mac the path to ‘Call script when torrent is complete’ is actually _Edit > Preferences > Transfers > Management_, and then the box is at the bottom. Maybe this is just for Mac, but it was a minor grievance looking for the right place to add the script.

**Comment by 8cylinder** [comment]
Your right, they have a different preferences layout.  I'll update the wiki.  Thanks!
