### ISSUE TITLE
remove command

### ISSUE THREAD

**Issue by funkyfuture** [8cylinder/tv-overlord#38]
unless i'm missing something, there's no way to remove a show from the database, right?

**Comment by 8cylinder** [comment]
The way it's done is `tvol editshow SHOWNAME`.  This brings up an interactive dialog where you can set the show's status to 'inactive'.  [Here are the details](https://github.com/8cylinder/tv-overlord/wiki/Command-line-reference#edit-show).

This makes the show appear to be gone but it can be set to 'active' later to start downloading it again.  Also inactive shows can be listed by `tvol --status=inactive --show-all`.

If you really want to delete the show completely, you need to open it in a sqlite editor and delete the show's record in the shows table.
