### ISSUE TITLE
Enhancement: Different shows, different sources

### ISSUE THREAD

**Issue by poo706** [8cylinder/tv-overlord#40]
Unless I'm missing it, it does not seem like tvol has the built-in ability to search some shows on bittorrent sites and other shows on nzb sites.  I'm getting around this by maintaining two sets of configs and databases.  My bash script temporarily renames the config and database files and performs two searches.  It also prompts me for a manual search, asks if I want BT or usenet, then temporarily renames files and runs the search.

**Comment by 8cylinder** [comment]
Interesting... it never occurred to me that someone would want to use both.  I can see two different config.ini's, but is there a reason for two different db's?

Something like this might work.  It would override the settings in config.ini:
`tvol download --method=nzb`
`tvol download --method=tor`

**Comment by poo706** [comment]
I like to get what I can from usenet because I don't use a VPN, but there are some of the more obscure shows like Difficult People (I see you're also a fan?) that have better results from BT.  Hmm, probably don't need two databases now that you mention it. I should merge those together and simplify my script a bit.  What you're describing would a more elegant way of accomplishing what I'm doing now, still performing two searches.  If you wanted to get really snazzy with it, you could add another column to the database and specify preferred search provider there.

**Comment by 8cylinder** [comment]
Thinking about this, what you are doing is probably the best method.  You have a db with only newsgroup shows and one with torrent shows and the appropriate config for each one.

So, I'm thinking the best way to handle this is to allow multiple configs.  This would mean that there wouldn't need to be any modification to the app except for a check at the start for which config to load.

`tvol --config=custom download`
`tvol --config='' download` would be the same as `tvol download`

And in the config dir, there would be:
```
config.ini
shows.sqlite3
config.custom.ini
shows.custom.sqlite3
```
This would allow any number of different configs.  And the user could download all of them with a simple bash script if they didn't want to type the config name each time:
```bash
for config in '' 'nzb' 'torrent' 'another_one'; do
    echo "Using $config config"
    tvol --config="${config}" list
    tvol --config="${config}" download
done
```

**Comment by poo706** [comment]
Why did you change your mind on multiple databases?  I've since combined them and all is well.  Sounds like a pretty good handling of the multiple configs.

**Comment by 8cylinder** [comment]
The reason I thought separate db would be good, was that a user would want to keep the shows separate.  For example, in your case, you would have an nzb config and a torrent config.  Then when you ran `tvol --config=nzb download` it would only iterate over the nzb shows, and then when you run `tvol --config=torrent download` it would only iterate over the torrent shows.

But if you have one db but different configs (like you do now), each time you run `tvol download` using the nzb config, it still iterates over all the shows and you have to `[s]kip` the torrent shows and vice versa when using the torrent config.

Another possibility is that if a user ran `tvol --config=nzb download` and `shows.nzb.sqlite3` didn't exist, then it would use the default database.  That way the option would exist that a user could use multiple configs with the same database.  It could also work the other way around, different db's but the same config (I don't know what the use case would be for that, but someone might find it useful).

**Comment by poo706** [comment]
Now that I have a common database, I like it.  I want to get what I can from usenet first, and if that doesn't work out, then fall back on bittorrent.  I guess what I was after was multiple configs more than anything.

**Comment by 8cylinder** [comment]
I have tweaked the 'named config' code.

Now, after creating a new config set, either of the new files can be deleted and then tvol will use the default files if any don't exist.  So, for your use case, you could:

1. `tvol config --create=NZB`

    This creates: `config.NZB.ini` and `shows.NZB.sqlite3`
2. `rm path/to/config/shows.NZB.sqlite3`
3. `tvol --config=NZB download`

    This will use `config.NZB.ini` and `shows.sqlite3`


https://github.com/8cylinder/tv-overlord/wiki/Config-file#multiple-configs-named-configs

**Comment by poo706** [comment]
I finally got around to upgrading to 1.4.3 and I really like your handling of multiple configs and/or db's.  I'm not a big fan of the `Using config.BT.ini` and `Warning: shows.BT.sqlite3 does not exist, using shows.sqlite3`, but only because it's a bit awkward in my bash script.  I can see why you'd want to output that for most others.

**Comment by 8cylinder** [comment]
I definitely don't need to say what config the user is using since they have already specified it on the command line but I like the warning that x file doesn't exist and its using the default one.

If I sent the warning message to stderr instead of stdout that would allow you to filter it out.  Tvol sends all messages to stdout including error messages, which is lazy on my part.  I should go through tvol and change error messages to use stderr.

This would send the warning to `/dev/null`:
`tvol list 2> /dev/null`  

Do you think that would solve your problem?

**Comment by poo706** [comment]
That would be perfect.  I actually already tried 2> /dev/null.  When it didn't work I chalked it up to simplicity, not laziness.  I gave you the benefit of the doubt.

**Comment by 8cylinder** [comment]
Errors are sent to stderr now in version 1.4.4 now.  If there are any more issues reopen this issue.
