### ISSUE TITLE
Telemetry data about users

### ISSUE THREAD

**Issue by 8cylinder** [8cylinder/tv-overlord#41]
I am contemplating an opt-in collection of telemetry data.  It would be **enormously** useful to know how tvol is being used.  Then development could focus on improving the things people are using.   For example, if 90% of the users are using nzb's instead of torrents then its obvious that energy should be spent on the nzb side of things.

An example of something I'd like to know is do users use the calendar?  The code for the calendar is pretty ugly so I'm unlikely to make any more changes to it since it works good enough for me.  But if it's being used a lot, then it should get some work and improvements.

This is a list of information I'd like to collect:

1. uuid -- An anonymous user id, so the data could be grouped by user.
1. timestamp -- The time tvol was used.
1. showcount -- The count of show in the db.
1. searchtype -- Nzb or torrent.
1. command -- The command used: add, calendar, config, copy, download, editshow, history, info, list, nondbshow or redownload.
1. version -- The version being used.

Feedback on this would be appreciated.

**Comment by Atrox** [comment]
Hey,

I'm using TV Overlord and I'm loving it. If you add the telemetry, please do it with an opt-in message on the first start (like yeoman for example [1]) and not like Homebrew with an environment variable. But other than that I see no problem on adding it.

I personally use TV Overlord just for the "automatic" downloads of new episodes. For tracking (when a new episode or season airs) and other things I use [trakt.tv](https://trakt.tv). I actually never used any other commands than `add`, `download` and `editshow`. Just my two cents :).

Thanks,
Atrox


[1]
```
? ==========================================================================
We're constantly looking for ways to make yo better!
May we anonymously report usage statistics to improve the tool over time?
More info: https://github.com/yeoman/insight & http://yeoman.io
========================================================================== (Y/n)
```

**Comment by poo706** [comment]
I'm not normally for this kind of thing, but I would be for this project.

**Comment by 8cylinder** [comment]
I've added **opt-in** telemetry data to the latest dev commit.  This is whats being collected:

1. timestamp
2. command - the command line arguments minus any show names or config names
3. tvol version
4. uuid - a random id
5. show count
6. search type - torrent or nzb
7. platform - Windows, Linux or MacOS (and version)
8. python version

The user is asked when the program is first run (or when a new config is first used) if collecting the data is ok.  This can be turned off or on in the config.ini as well, and if a user uses named configs, this can be different per config.

This code runs in a separate thread so it won't block tvol if the connections are slow.
