### ISSUE TITLE
TVshow updates wrong?

### ISSUE THREAD

**Issue by metracy** [8cylinder/tv-overlord#42]
Found this with mr robot:

The last episode broadcast was S02E10.
Start downloading the [f]irst, [l]atest or season and episode?
Type "f", "l" or a season and episode number: 02 10

Mr. Robot S02E09, added

**Comment by 8cylinder** [comment]
In the db, I store the **last** downloaded episode which means I subtract 1 from the requested episode, but when I display the episode I should re-adjust the number to add 1.

When you run `tvol list` you'll see the correct episode listed.

Thanks for the bug report!

**Comment by 8cylinder** [comment]
Fixed in latest dev branch.
