### ISSUE TITLE
Override application used to open links

### ISSUE THREAD

**Issue by floreal** [8cylinder/tv-overlord#44]
It would be great if instead of opening links in the default brother we could choose an app or a custom script.

Then it would be possible to open a link with peerflix [1], and then directly stream videos in a media player

[1] https://github.com/mafintosh/peerflix

**Comment by floreal** [comment]
Hum looks like it already does that :) I'm closing it

**Comment by 8cylinder** [comment]
You can!  In config.ini you can set the `client` field to whatever you want.

https://github.com/8cylinder/tv-overlord/wiki/Config-file

client: COMMAND 

If this is set, it will override the default client for your os. This can be used to run a command line bittorrent client. It must have this flag as part of it: `{magnet}`, which will get replaced with the downloaded magnet link. Also, any file paths with a space must be enclosed in quotes. The `{magnet}` tag can be used more than once if necessary
