### ISSUE TITLE
Option to exclude string from search

### ISSUE THREAD

**Issue by shrx** [8cylinder/tv-overlord#53]
Could you add an option to filter out the search matches that include a given string?

**Comment by 8cylinder** [comment]
Can you give me some use cases for this?  

It would be fairly strait forward to add it globally.  I could add a filter list to config.ini:
`filters: eztv, 720, another string, and another`
and it would be applied to all shows.

But if you are thinking about applying it on a per show level that gets a little more complicated from a UI perspective.  It would have to be added via `tvol editshow SHOWNAME` and I am reluctant to add more fields to that command unless there is a strong use for it.

**Comment by shrx** [comment]
Yeah there are multiple shows that can be named similarly. For example "Angel" and "Angel from hell". If you search for "Angel", you would like to filter out the results containing "from hell".

**Comment by 8cylinder** [comment]
That makes sense.  I've added a global filter list in the last commit.  It should be on pypi soonish.

Something to consider is that this could cause some problems. What if you also want a show called 'cowboys from hell' and you've forgotten that there is a 'from hell' filter.  You would never get any results.

**Comment by shrx** [comment]
Yeah it would work better as an optional argument: `tvol download "angel" -f "from hell"`

**Comment by 8cylinder** [comment]
I've added a `--filters` option to the download command.  

It takes the same arguments as the `filters:` line in config.ini.  Except that if one of the filters has a space, then they all need to be wraped in quotes.  This will also override any set in the config.  So if the config has `filters: 720, eztv` and then `--filter 2017` is used on the command line, only `2017` will get applied.

**Comment by 8cylinder** [comment]
I might add it on a per show level, but I think this is good enough for now.

**Comment by shrx** [comment]
Thanks, looks good.
