### ISSUE TITLE
Auto download options

### ISSUE THREAD

**Issue by ChillarAnand** [8cylinder/tv-overlord#54]
Right now, to download entire show, user has to select each and every episode. 

It is better if there is an option to auto download based on seeders, size e.t.c

**Comment by 8cylinder** [comment]
I think you're describing one of two scenarios.

1. Having tvol automatically download episodes as they come out based on some criteria.
2. An older show that has all its episodes available to download and you've added it to tvol.

The first scenario I've though about off and on for a while, but it would mean changing tvol significantly and there are other applications that do automated downloads already.  So I don't see much to gain from duplicating what someone else has done well already.  If that's the kind of functionality you're looking for I recommend something like flexget.

The second scenario is a pain.  Adding complete seasons can be a bit of a hassle, but I don't see a way around that.  For obscure shows, getting all the episodes can be difficult.  They end up coming from different search engines, some are 720p, while some are only 420p.  Sometimes an episode will have less that 10 seeders while another one in the same season might have 200.  Coming up with rules to cover all these scenarios would be a lot of work.

So, I feel the best way is to just select them one by one.  It goes pretty fast and you get the chance to make sure your getting the right thing.  I don't think its worth the effort for a sort of edge case.
